version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: people
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ICanDoIt!
      MYSQL_ROOT_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3307:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      mysql-network:
        aliases:
          - mysql

  app:
    build: ./python-app
    container_name: python
    depends_on:
      - db
    restart: always
    ports:
      - '5000:5000'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
